from typing import Optional
import redis

class ConfigurationError(Exception): ...

def get_redis_url() -> str: ...

def get_redis_client(url: Optional[str] = None) -> redis.Redis: ...

async def get_async_redis_client(url: Optional[str] = None) -> redis.asyncio.Redis: ...

def clear_cache(url: Optional[str] = None) -> int: ...

async def clear_cache_async(url: Optional[str] = None) -> int: ... 